### ISSUE TITLE
Codemods should be able to be co-located with normal NPM packages

### ISSUE THREAD

**Issue by danieldelcore** [CodeshiftCommunity/CodeshiftCommunity#48]
Codemods should be shareable via normal npm packages.

This would mean that a package like react could create a `codeshift.config.js` and link transforms. 

Codeshift cli will then pull the package and attempt to locate a config file. If that file is not found, it will attempt to pull a codemod from the community folder.

**Comment by kiprasmel** [comment]
I like this idea. Ideally we'd have another, even simpler way - instead of installing the package from npm, the cli would use a provided path to- / name of- the local package, i.e. the codemod repo (or a repo w/ a codemod) would be cloned from git -- so that it's easier to both update and consume internally, w/o publishing to npm every time.

Ideally w/o having to build either and using ts-node directly.
